version: "0.2"
words:
  - beholdenkey
  - Buildah
  - CODEOWNERS
  - codeql
  - commitlint
  - conventionalcommits
  - Crossplane
  - datasource
  - datasources
  - defenseunicorns
  - doublestar
  - indentless
  - kubeconfig
  - metallb
  - ossf
  - Parens
  - sarif
  - servicelb
  - traefik
  - yolo
