name: Metadata

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  title_check:
    runs-on: ubuntu-latest
    name: Validate PR Title
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional@19.1.0
          npm install --save-dev @commitlint/cli@19.2.1

      - name: Lint PR title
        env:
          pull_request_title: ${{ github.event.pull_request.title }}
        run: echo "$pull_request_title" | npx commitlint